title        = "SDA's Notes"
relativeURLs = true
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
PygmentsCodeFences = false
PygmentsStyle = "monokai"
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A collection of my personal notes."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  footerRight = "Made with &#10084; by <a href=\"https://github.com/SDAChess\">Simon Scatton</a>"
  # Metadata mostly used in document's head
  description = "SDA's Personal notes"
  keywords = "homepage, notes"
  images = [""]
  [[params.social]]
    name = "email"
    url  = "mailto:simon.scatton@epita.fr"

  [[params.social]]
    name = "github"
    url  = "https://github.com/SDAChess"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "SDA's Notes"
    subtitle = "A collection of my personal notes"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "SDA's Personal Notes"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "maths"
    name       = "Maths"
    url        = "/maths/"
  [[menu.main]]
    identifier = "physics"
    name       = "Physics"
    url        = "/physics/"
  [[menu.main]]
    identifier = "algo"
    name       = "Algorithmic"
    url        = "/algo/"
